# Generated by Django 3.0.4 on 2020-04-20 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, upload_to='foto_perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
                ('fecha_inicio', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('fecha_fin', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('nivel_prioridad', models.CharField(choices=[('', ''), ('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Moderada', 'Moderada'), ('Baja', 'Baja')], default='', max_length=20)),
                ('notas', models.TextField(max_length=300)),
                ('estado_tarea', models.CharField(choices=[('', ''), ('Abierta', 'Abierta'), ('Asignada', 'Asignada'), ('En proceso', 'En proceso'), ('Finalizada', 'Finalizada')], default='', max_length=20)),
                ('responsable', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appGestorProyectos.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
                ('fecha_inicio', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('fecha_fin', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('presupuesto', models.IntegerField(default=0)),
                ('nombre_cliente', models.CharField(default='', max_length=20)),
                ('apellidos_cliente', models.CharField(default='', max_length=50)),
                ('email_cliente', models.EmailField(default='', max_length=100)),
                ('telefono_cliente', models.IntegerField(default=0)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestorProyectos.Empleado')),
                ('tarea', models.ManyToManyField(to='appGestorProyectos.Tarea')),
            ],
        ),
    ]
